# Change these first
owner: GhostDog98 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ghostoverflow.gay
    url: https://ghostoverflow.gay?token=$HEADER_SECRET
  - name: ai.ghostoverflow.gay
    url: https://ghostoverflow.gay?token=$HEADER_SECRET
  - name: api.ghostoverflow.gay
    url: https://api.ghostoverflow.gay/endpoints?token=$HEADER_SECRET
  - name: jellyfin.ghostoverflow.gay
    url: https://jellyfin.ghostoverflow.gay?token=$HEADER_SECRET
  - name: lufi.ghostoverflow.gay
    url: https://lufi.ghostoverflow.gay?token=$HEADER_SECRET
  - name: Wikipedia
    url: https://en.wikipedia.org
assignees:
  - GhostDog98

status-website:
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #baseUrl: /upptime
  cname: uptime.ghostoverflow.gay
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Stats for infrastructure
  introTitle: "**Upptime** status for ghostoverflow.gay."
  introMessage: Ruh roh scooby
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
